cmd/frontend/src/App/app.css, cmd/frontend/src/Components/PresentationalComponents/Table/Table.js, cmd/frontend/src/Components/PresentationalComponents/Table/XAxisLabel/XAxisLabel.js, cmd/frontend/src/Components/PresentationalComponents/Table/YAxisLabel/YAxisLabel.js, cmd/frontend/src/Components/SmartComponents/AppLayout/AppLayout.js, cmd/frontend/src/Components/SmartComponents/Tabs/Tabs.js, cmd/frontend/src/constants.js
=> Add axis labels

cmd/frontend/src/App/app.css, cmd/frontend/src/Components/SmartComponents/AppLayout/AppLayout.js
=> Enhance grid appearance 

pkg/dispatcher/operator/workers/controller.go, pkg/util/hash.go
=> share the generation hash logic

cmd/result-collector/main.go, pkg/result-collector/controller.go
=> remove threadiness in result-controller calculation controller

.gitignore, cmd/dashboard/frontend/.eslintrc.yaml, cmd/dashboard/frontend/package-lock.json, cmd/dashboard/frontend/package.json, cmd/dashboard/frontend/services/Calculations.js, cmd/dashboard/frontend/services/http/Client.js, cmd/dashboard/frontend/services/http/Http.js, cmd/dashboard/frontend/src/App/app.css, cmd/dashboard/frontend/src/App/index.js, cmd/dashboard/frontend/src/Components/PresentationalComponents/EmptyStateSpinner/EmptyStateSpinner.js, cmd/dashboard/frontend/src/Components/PresentationalComponents/Table/Table.js, cmd/dashboard/frontend/src/Components/PresentationalComponents/Table/XAxisLabel/XAxisLabel.js, cmd/dashboard/frontend/src/Components/PresentationalComponents/Table/YAxisLabel/YAxisLabel.js, cmd/dashboard/frontend/src/Components/SmartComponents/AppLayout/AppLayout.js, cmd/dashboard/frontend/src/Components/SmartComponents/Tabs/Tabs.js, cmd/dashboard/frontend/src/constants.js, cmd/dashboard/frontend/src/routes.js, cmd/dashboard/frontend/webpack.common.js, cmd/dashboard/frontend/webpack.dev.js, cmd/dashboard/frontend/webpack.prod.js
The PR in more details: 
- Add eslint for syntax consistency 
- introduce `Axios` Client to the HTTP request
- consume data from the backend and accordingly render the grid. The cell is rendered based on the `phase` of the calculation. 
1.  created -> green
1. processing -> orange
=> Consume backend data

cmd/dashboard/backend/main.go
To create a calculation:
Send a POST request to /calculations/create endpoint with
params in json format with values teff and logG.
To delete a calculation:
Send a DELETE request to /calculations/delete/calc-name
cc @katerinapat 
=> add the ability to create/delete calculations

cmd/dispatcher/main.go, pkg/dispatcher/operator/calculations/controller.go, pkg/dispatcher/operator/operator.go, pkg/dispatcher/operator/workers/controller.go, pkg/result-collector/controller.go, pkg/util/config.go, pkg/util/taskqueue.go, pkg/worker/executor/executor.go, pkg/worker/operator.go
=> remove dead code, add/remove comments

.github/workflows/go.yml
This enables to run the basic go tests
=> create go.yml file

cmd/dashboard/backend/main.go, pkg/dispatcher/operator/workers/controller.go, pkg/util/calculations.go
=> share a create new minimum calculation in util package

cmd/dashboard/backend/main.go, cmd/dispatcher/main.go, cmd/janitor/main.go, cmd/worker/main.go, pkg/dispatcher/operator/operator.go, pkg/dispatcher/operator/workers/controller.go, pkg/worker/controller.go, pkg/worker/operator.go
=> initialize context in all of the components

cmd/dashboard/backend/main.go, cmd/janitor/main.go, cmd/janitor/main_test.go, cmd/result-collector/main.go, deploy/calculations_rbac.yaml, pkg/apis/calculations/register.go, pkg/apis/calculations/v1/doc.go, pkg/client/clientset/versioned/clientset.go, pkg/client/clientset/versioned/fake/clientset_generated.go, pkg/client/clientset/versioned/fake/register.go, pkg/client/clientset/versioned/scheme/register.go, pkg/client/clientset/versioned/typed/calculations/v1/calculation.go, pkg/client/clientset/versioned/typed/calculations/v1/calculations_client.go, pkg/client/clientset/versioned/typed/calculations/v1/fake/fake_calculation.go, pkg/client/clientset/versioned/typed/calculations/v1/fake/fake_calculations_client.go, pkg/client/informers/externalversions/calculations/v1/calculation.go, pkg/client/informers/externalversions/factory.go, pkg/client/informers/externalversions/generic.go, pkg/dispatcher/operator/operator.go, pkg/dispatcher/operator/workers/controller.go, pkg/worker/controller.go, pkg/worker/operator.go
=> update calculations groud and fix RBACs

cmd/dashboard/backend/main.go, pkg/util/calculations.go
=> [dashboard/backend] add new flags and a new GET calculations by teff/logG enpoint. 

cmd/result-collector/main.go, pkg/result-collector/controller.go, pkg/result-collector/controller_test.go, pkg/util/labels.go
=> [result-collector] apply a label to the calculation when results are collected

cmd/dashboard/backend/main.go
=> allow dashboard backend to run in a non-dry mode

cmd/dashboard/frontend/src/Components/Presentational/CalcInfo/CalcInfo.js, cmd/dashboard/frontend/src/Components/Presentational/Notification/Notification.js, cmd/dashboard/frontend/src/Components/Presentational/ToolBar/ToolBar.js, cmd/dashboard/frontend/src/Components/SmartComponents/Pages/Dashboard.js, cmd/dashboard/frontend/src/services/Calculations.js, cmd/dashboard/frontend/src/services/http/Http.js
Delete an existing calculation and reload the grid
=> Add option to delete a calculation

cmd/dashboard/frontend/src/Components/Presentational/CalcInfo/CalcInfo.js, cmd/dashboard/frontend/src/Components/Presentational/Grid/Grid.js
=> Add toolip on hover

.github/workflows/docker-publish-dispatcher.yml, .github/workflows/docker-publish-janitor.yml, .github/workflows/docker-publish-result-collector.yml, images/janitor/Dockerfile
=> add github actions for publishing the rest of the images

.github/workflows/docker-publish-dispatcher.yml, .github/workflows/docker-publish-janitor.yml, .github/workflows/docker-publish-result-collector.yml, .github/workflows/docker-publish-worker.yml
=> add the repository name in the images link id

cmd/dashboard/backend/main.go
=> don't build a literal client on dry run

cmd/dashboard/frontend/package-lock.json
ran npm audit fix to update vulnerabilities
=> Audit fix 04/11

cmd/worker/main.go
=> change atlas files default location

cluster/worker/ds.yaml
=> fix vega worker deployment flags

README.md
=> add a README.md file

images/dashboard/frontend/Dockerfile
=> change cmd to entrypoin to frontend's dockerfile

cmd/dashboard/frontend/package.json
=> add port in the backend url

cmd/dashboard/frontend/package.json
=> add the external route url to front end endpoint

cmd/dashboard/frontend/package.json
Reverts vega-project/ccb-operator#72
=> Revert "add the external route url to front end endpoint"

cluster/dashboard/backend.yaml, cluster/dashboard/frontend.yaml
=> add the dashboard deployment files

cmd/dispatcher/main.go, pkg/dispatcher/operator/operator.go
This PR adds the change that you get the password for redis DB from file instead of being hardcoded.
/cc @droslean 
Signed-off-by: Daniel Odvarka <dodvarka@10.0.0.7>
=> retrieving the redis password from a file

cmd/dispatcher/main.go, pkg/dispatcher/operator/operator.go, pkg/dispatcher/operator/workers/controller.go, pkg/dispatcher/operator/workers/controller_test.go
This PR contains changes about the flag that retrieves the redis sorted set name. 
cc @droslean 
Signed-off-by: Daniel Odvarka <odvarkaadaniel@gmail.com>
=> added flag for getting the name of the redis sorted set

.travis.yml
=> remove travis configuration

cmd/apiserver/main.go, cmd/apiserver/server.go
=> allow apiserver to authenticate using a session token

Makefile, cluster/apiserver/apiserver.yaml, cmd/apiserver/main.go, cmd/apiserver/server.go
=> Add apiserver deployment files and check if no session tokens are passed

cmd/apiserver/main.go, cmd/apiserver/server.go
=> use a stable calculation client instead

cluster/apiserver/apiserver.yaml, cmd/apiserver/main.go
Added /healtz endpoint and liveness probe to the deployment file.
cc @droslean
=> Add a liveness health probe in api server component 

cmd/apiserver/server.go
=> add the status code in headers and refactor the response errors

cmd/apiserver/main.go, cmd/apiserver/simulator.go
Created a new file, added `ctx` and `fakeClient` to a struct so they aren't appearing every time as function parameters. 
@droslean 
Signed-off-by: Daniel Odvarka <odvarkaadaniel@gmail.com>
=> Split the dry run logic from main into a new file.

cluster/apiserver/apiserver.yaml
=> add oauth proxy in apiserver deployment

cmd/apiserver/main.go
Those had to be removed in https://github.com/vega-project/ccb-operator/pull/103 but we missed them.
@odvarkadaniel FYI
=> remove duplicated flags related to simulator

Makefile, cluster/dispatcher/deploy.yaml, cluster/redis/redis.yaml
=> add a redis deployment template

cluster/apiserver/apiserver.yaml
=> update the apiserver deployment to accept bearer token through proxy

cmd/apiserver/server.go
=> add cors friendly headers in api server endpoints

cmd/apiserver/server_test.go
Could you please take a look in any of the functions? I am not really certain if I need the part with the http.NewRequest() etc.. Thank you
@droslean 
Signed-off-by: Daniel Odvarka <odvarkaadaniel@gmail.com>
=> unit tests for server operation in api server

pkg/util/taskqueue.go
=> prevent from requeuing deleted calculations

pkg/apis/calculations/v1/types.go, pkg/dispatcher/operator/workers/controller.go, pkg/dispatcher/operator/workers/controller_test.go
=> Prioritize calculation created by humans

pkg/dispatcher/operator/workers/controller.go, pkg/dispatcher/operator/workers/controller_test.go
=> fix panic when sorting, add more test cases

cmd/apiserver/main.go, cmd/apiserver/server.go
=> Add the ability to download the results by teff,logG or by calc id

cluster/apiserver/apiserver-nooauth.yaml, cluster/apiserver/apiserver.yaml
=> add calculation results volume in apiserver deployment

cmd/dispatcher/main.go, pkg/dispatcher/operator/calculations/controller.go
Reverts vega-project/ccb-operator#119
=> Revert "Expose prometheus metrics"

pkg/dispatcher/operator/calculations/controller.go
Sorry about that, forgot to add a line that increments the values. The metrics didnt get exposed then. @droslean 
Signed-off-by: odvarkadaniel <odvarkaadaniel@gmail.com>
=> expose prometheus metrics

pkg/dispatcher/operator/calculations/controller.go
@droslean 
Signed-off-by: odvarkadaniel <odvarkaadaniel@gmail.com>
=> remove double vega for prometheus query

pkg/dispatcher/operator/workers/controller.go
@droslean 
Signed-off-by: odvarkadaniel <odvarkaadaniel@gmail.com>
=> metrics for pod status

pkg/dispatcher/operator/calculations/controller.go, pkg/dispatcher/operator/workers/controller.go
=> code was panicing when run - metrics were placed before error handling

pkg/dispatcher/operator/calculations/controller.go, pkg/dispatcher/operator/workers/controller.go, pkg/result-collector/controller.go, pkg/util/taskqueue.go, pkg/worker/controller.go
=> make sure that deleted keys don't requeue in the taskqueue

pkg/dispatcher/operator/calculations/controller.go, pkg/dispatcher/operator/workers/controller.go, pkg/result-collector/controller.go, pkg/worker/controller.go
=> don't requeue objects on delete function

pkg/worker/executor/executor.go
=> stop the execution when a step fails

cmd/worker/main.go, pkg/worker/executor/executor.go
=> respect new lines in initial logger formatter

pkg/worker/executor/executor.go
=> dump command output when a step fails

.github/workflows/docker-publish-apiserver.yml, .github/workflows/docker-publish-dispatcher.yml, .github/workflows/docker-publish-janitor.yml, .github/workflows/docker-publish-result-collector.yml, .github/workflows/docker-publish-worker.yml
=> add golang version on push steps in all workflows

cmd/worker/main.go, pkg/worker/controller.go, pkg/worker/executor/executor.go, pkg/worker/operator.go
=> refactor worker to use the controller runtime library

cmd/result-collector/main.go, pkg/result-collector/controller.go, pkg/result-collector/controller_test.go
=> refactor result-collector to use the controller runtime library

cmd/apiserver/main.go, cmd/apiserver/server.go, cmd/apiserver/server_test.go, cmd/apiserver/simulator.go
=> refactor apiserver to use the controller runtime library

cmd/apiserver/server.go
=> [apiserver] add namespace when creating new calculation

cmd/apiserver/main.go
=> [apiserver] pass the namespaces in the server's struct

pkg/worker/executor/executor.go
=> fix dumping output file location

pkg/worker/executor/executor.go
=> change the permissions to 777 when creating a calculation folder

pkg/worker/controller.go, pkg/worker/controller_test.go, pkg/worker/operator.go
=> register worker after the cache has been initialized

pkg/worker/controller.go, pkg/worker/workerpools/workerpools.go, pkg/worker/workerpools/workerpools_test.go
=> introduce the workerpool controller

pkg/worker/controller.go
=> stop registering workerpools in calculation controller

pkg/worker/workerpools/workerpools.go
=> small fixes in the workerpool controller

cluster/calculations/rbacs.yaml, pkg/dispatcher/workerpools/controller.go
=> small fixes in the dispatcher workerpool controller

cluster/calculations/rbacs.yaml, pkg/dispatcher/workerpools/controller.go, pkg/dispatcher/workerpools/controller_test.go
=> assign namespace while creating a calculation

pkg/dispatcher/workerpools/controller.go, pkg/worker/workerpools/workerpools.go
=> update calculation in bulk on processing

pkg/worker/controller.go
=> fix panic while updating the status in worker pool

pkg/dispatcher/calculations/controller.go, pkg/dispatcher/calculations/controller_test.go, pkg/dispatcher/workerpools/controller.go, pkg/dispatcher/workerpools/controller_test.go, pkg/worker/controller.go
=> update status in calculation bulk when processing a calculation

pkg/dispatcher/workerpools/controller.go, pkg/dispatcher/workerpools/controller_test.go
=> allow dispatcher to create calculations for all available workers

cluster/worker/ds.yaml, cmd/worker/main.go, pkg/dispatcher/workerpools/controller.go, pkg/dispatcher/workerpools/controller_test.go, pkg/dispatcher/workers/controller.go, pkg/worker/controller.go, pkg/worker/operator.go, pkg/worker/workerpools/workerpools.go, pkg/worker/workerpools/workerpools_test.go
=> use the nodename to map the worker in workerpools

pkg/worker/workerpools/workerpools.go
=> update the worker's name when reconciling the workerpools

pkg/dispatcher/workerpools/controller_test.go, pkg/worker/workerpools/workerpools.go, pkg/worker/workerpools/workerpools_test.go
=> refactor workerpool tests and add some logging

pkg/worker/workerpools/workerpools.go
=> pass the hostname to the reconciler

pkg/apis/workers/v1/types.go, pkg/apis/workers/v1/vegaproject.io_workerpools.yaml, pkg/worker/workerpools/workerpools.go
=> some refactoring in workerpools types and registration 

pkg/worker/controller.go
=> update worker in pool when processing a calculation

pkg/worker/controller.go
=> fix updating the worker status in pool

pkg/worker/controller.go
=> update worker pool when a calculation fails

pkg/dispatcher/workers/controller.go
=> [dispatcher] enable onDelete events in worker pods controller

pkg/dispatcher/workers/controller.go
=> compare worker name with pod name on delete events

cmd/dispatcher/main.go, pkg/dispatcher/bulks/controller.go, pkg/dispatcher/bulks/controller_test.go
=> fix the package name in bulks controller and load it in dispatcher

pkg/dispatcher/bulks/controller.go
=> fix calculation bulks indexing cache

pkg/dispatcher/bulks/controller.go, pkg/dispatcher/bulks/controller_test.go
=> fix error message and the expected variable name in tests

pkg/dispatcher/bulks/controller.go, pkg/dispatcher/bulks/controller_test.go
=> include the name of the bulk while registering in worker pool

cmd/apiserver/main.go, cmd/apiserver/server.go, cmd/apiserver/server_test.go
=> introduce calculation bulks to the api server

pkg/worker/executor/executor.go
=> wait to allow the nfs to create the fort.95 file

pkg/worker/executor/executor.go
Reverts vega-project/ccb-operator#181
=> Revert "wait to allow the nfs to create the fort.95 file"

pkg/worker/executor/executor.go
=> don't create the fort.95 file

pkg/worker/executor/executor.go
Reverts vega-project/ccb-operator#183
=> Revert "don't create the fort.95 file"

cmd/apiserver/server.go, cmd/apiserver/server_test.go, cmd/apiserver/simulator.go, pkg/dispatcher/workerpools/controller.go, pkg/dispatcher/workerpools/controller_test.go, pkg/result-collector/controller_test.go, pkg/util/calculations.go
Signed-off-by: Daniel Odvarka <odvarkaadaniel@gmail.com>
=> newCalculation takes a calculation object and steps are not hardcoded

pkg/worker/executor/executor.go
=> fix passing arguments to the execution command

pkg/dispatcher/workerpools/controller_test.go, pkg/util/calculations.go
=> default the synspec step to force running via a bash session

pkg/dispatcher/workerpools/controller_test.go, pkg/util/calculations.go
=> remote unnecessary quotes in synspec step args

pkg/dispatcher/calculations/controller.go, pkg/util/calculations.go, pkg/util/workers.go, pkg/worker/controller.go, pkg/worker/executor/executor.go, pkg/worker/operator.go
=> Refactor controllers to manage a completed calculation

pkg/worker/executor/executor.go
=> fix arguments when initializing the executor

pkg/dispatcher/workerpools/controller.go, pkg/util/workers.go
=> get the calculation bulks based on their registered time and ignore the deleted ones

pkg/result-collector/controller.go
=> Improve logging while processing the calculation results

pkg/result-collector/controller.go
=> [results-collector] refactor the operations related to result gathering

pkg/dispatcher/workerpools/controller.go
=> pass input files to the created calculation

pkg/worker/executor/executor.go
=> fix inputfile full path when creating symlinks

pkg/dispatcher/workerpools/controller.go
=> [dispatcher] add more logging while creating a calculation

cmd/worker/main.go
=> remove deprecated flag validation in worker

pkg/worker/executor/executor.go
=> log the errors when the calculation fails on pipelines

pkg/worker/executor/executor.go
=> dump the output on either of the exit status of the step command

pkg/apis/calculationbulk/v1/types.go, pkg/apis/calculationbulk/v1/vegaproject.io_calculationbulks.yaml, pkg/dispatcher/workerpools/controller.go, pkg/dispatcher/workerpools/controller_test.go, pkg/util/labels.go, pkg/worker/executor/executor.go
=> introduce the rootFolder field in the calculation bulks

images/apiserver/Dockerfile, images/dashboard/frontend/Dockerfile, images/janitor/Dockerfile, images/result-collector/Dockerfile, images/worker/Dockerfile
Reverts vega-project/ccb-operator#214
=> Revert "change base of the images to centos:8 and remove dashboard"

pkg/dispatcher/bulks/controller.go
=> reserve the worker first before creating a calculation to avoid races

pkg/dispatcher/bulks/controller.go, pkg/dispatcher/bulks/controller_test.go
=> update worker's status in pool when failed to create a calculation

pkg/worker/controller.go
=> ignore deleted calculations in worker

go.mod, go.sum, pkg/apis/calculationbulkfactory/v1/types.go, pkg/apis/calculationbulkfactory/v1/vegaproject.io_calculationbulkfactories.yaml, pkg/apis/calculationbulkfactory/v1/zz_generated.deepcopy.go, pkg/dispatcher/calculations/controller.go, pkg/dispatcher/factory/controller.go, pkg/util/labels.go, pkg/worker/executor/executor.go
=> initial implementation of the calculation bulk factory controller

cluster/calculations/rbacs.yaml, cluster/dispatcher/deploy.yaml, cmd/dispatcher/main.go
=> enable the calculation bulk factory controller

pkg/apis/calculationbulkfactory/v1/types.go, pkg/apis/calculationbulkfactory/v1/vegaproject.io_calculationbulkfactories.yaml, pkg/dispatcher/factory/controller.go
=> stop operating on a bulk factory when the bulk was created

pkg/apis/calculationbulkfactory/v1/types.go, pkg/apis/calculationbulkfactory/v1/vegaproject.io_calculationbulkfactories.yaml, pkg/apis/calculationbulkfactory/v1/zz_generated.deepcopy.go, pkg/dispatcher/factory/controller.go
=> include input files in the calculation bulk factories

pkg/dispatcher/calculations/controller.go
=> prevent operation on the bulks for factory calculations

pkg/dispatcher/factory/controller.go
=> create the bulk file into the root folder

pkg/apis/calculationbulk/v1/types.go, pkg/apis/calculationbulk/v1/vegaproject.io_calculationbulks.yaml, pkg/apis/calculationbulk/v1/zz_generated.deepcopy.go, pkg/dispatcher/bulks/controller.go, pkg/dispatcher/calculations/controller.go, pkg/dispatcher/calculations/controller_test.go, pkg/util/calculations.go, pkg/util/labels.go
=> initial implementation of the post calculations in bulks

cmd/apiserver/main.go, cmd/apiserver/server.go
=> implement an endpoint for dowloading the results for calculations

pkg/pipelines/vega.go, pkg/pipelines/vega_test.go
=> reconstruct the Kuruz input file variables, respect the decimal points

cmd/results-handler/main.go, cmd/worker/main.go, pkg/grpc/client.go, pkg/grpc/options.go, pkg/grpc/server.go, pkg/worker/executor/executor.go, pkg/worker/operator.go
=> send results to the database via gRPC for vega pipelines

pkg/worker/executor/executor.go
=> cleaning up temporary folders when the calculation finishes on the vega pipeline

images/worker/Dockerfile
=> change the base image for the worker component
